[package]
name = "world_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
# Less engine logs
log = { version = "*", features = [
  "max_level_debug",
  "release_max_level_warn",
] }
